### ISSUE TITLE
Teacher (post creator) cannot vote 

### ISSUE THREAD

**Issue by donhinkelman** [sapporomatt/moodle-mod_reactforum#12]
Although Reactforum was designed for students only to vote or "react" on the forum, sometimes it is good to allow the teacher or forum creator to vote or "react". Could a setting be added to allow teacher voting?

**Comment by jlhollowell** [comment]
This one is also included in Adam's pull request I believe. The details are:

In lib.php around line 3817 change:

$buttonattrs['disabled'] = 'disabled';

to

$buttonattrs['enabled'] = 'enabled';

and in react_ajax.php 

around line 60, comment out the following (as shown)
//if ($post->userid == $USER->id) {
//    throw new moodle_exception('error', 'mod_reactforum');
//}

and later in the same file (react_ajax.php) around line 117 change:

$item['enabled'] = false;

to

$item['enabled'] = true;

;-)

**Comment by donhinkelman** [comment]
Thanks, Jason. All notes here in github, so Mo can understand what you and Adam did.  Issue closed!
